### ISSUE TITLE
Is it possible to do multiagent in pomdp-py?

### ISSUE THREAD

**Issue by disadone** [h2r/pomdp-py#14]
Excellent framework and clear examples!
I am new to POMDP. I wonder is it possible to implement decentralized like DEC-Tiger (Nair et.al. 2003) or centralized POMDP? Thanks!

**Comment by zkytony** [comment]
DEC-POMDP is not supported yet, but I bet it wouldn't be too hard to implement based on current interfaces, I think it just needs a new `Planner` whose `plan` function takes in multiple `Agent` objects. I currently don't have plans to do this but it'd be awesome if you try it!

**Comment by disadone** [comment]
I will try! Maybe several months later, there is a new planner...or not.

**Comment by zkytony** [comment]
I'm sure you know this, but just as a reference, you can find more info (and code) about DEC-POMDP from here: http://rbr.cs.umass.edu/camato/decpomdp/

**Comment by disadone** [comment]
I only know the "new book" in the website, code really helps! Thank you!

**Comment by zkytony** [comment]
Will close this for now. Reopen if there's more to discuss!
