### ISSUE TITLE
ModuleNotFoundError: No module named 'pomdp_py.framework.basics'

### ISSUE THREAD

**Issue by cj9208** [h2r/pomdp-py#17]
I follow the install instruction and successfully install the package. But when I try to run the example, it gives the following error. No idea what happened. 
```
python -m pomdp_problems.tiger.tiger_problem
Traceback (most recent call last):
  File "/Users/chenjie/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/chenjie/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/chenjie/opt/anaconda3/lib/python3.8/site-packages/pomdp_problems/tiger/tiger_problem.py", line 38, in <module>
    import pomdp_py
  File "/Users/chenjie/opt/anaconda3/lib/python3.8/site-packages/pomdp_py/__init__.py", line 4, in <module>
    from pomdp_py.framework.basics import *
ModuleNotFoundError: No module named 'pomdp_py.framework.basics'
```

**Comment by zkytony** [comment]
That is strange. Which command did you run to install it?

I just tried with a new python 3.8 virtualenv. I tried both `pip install pomdp-py` and installing from cloned repo. Both worked. Did you run `make build`?

**Comment by cj9208** [comment]
I am using this command: pip install pomdp-py (just follow the tutorial
https://h2r.github.io/pomdp-py/html/installation.html)
[image: image.png]

and test with your example python -m pomdp_problems.tiger.tiger_problem

My python version is also 3.8. I just tried again and the same thing
happened.

[image: image.png]


best regards,

Chen Jie, PhD Candidate,
Department of Systems Engineering and Engineering Management
The Chinese University of Hong Kong
***@***.***, ***@***.***

**Comment by cj9208** [comment]
One more thing to say, I tried on a windows desktop and macbook. Both give
the same results. That is why I raise the issue.

best regards,

Chen Jie, PhD Candidate,
Department of Systems Engineering and Engineering Management
The Chinese University of Hong Kong
***@***.***, ***@***.***

**Comment by zkytony** [comment]
@cj9208 I can't view the attached images. Can you upload them again?

**Comment by zkytony** [comment]
I just ran this on Ubuntu 18.04:
``` cmd
$ virtualenv -p $(which python3) testenv2
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local'
/usr/lib/python3/dist-packages/virtualenv.py:1086: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /media/kz-wd-ssd/repo/_tmp/testenv2/bin/python3
Also creating executable in /media/kz-wd-ssd/repo/_tmp/testenv2/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

$ source testenv2/bin/activate

(testenv2) $ pip install pomdp-py
Collecting pomdp-py
  Using cached pomdp_py-1.2.4.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.3 MB)
Collecting Cython
  Using cached Cython-0.29.24-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
...
Successfully installed Cython-0.29.24 cycler-0.10.0 kiwisolver-1.3.1 matplotlib-3.4.2 networkx-2.6.2 numpy-1.21.1 opencv-python-4.5.3.56 pillow-8.3.1 pomdp-py-1.2.4.5 pygame-2.0.1 pygraphviz-1.7 pyparsing-2.4.7 python-dateutil-2.8.2 scipy-1.7.1 six-1.16.0

(testenv2) $ python -m pomdp_problems.tiger.tiger_problem
** Testing value iteration **
==== Step 1 ====
True state: tiger-right
Belief: [(TigerState(tiger-right), 0.5), (TigerState(tiger-left), 0.5)]
Action: listen
Reward: -1
>> Observation: tiger-right...
```

**Comment by cj9208** [comment]
It must be the problem of the platform. I tried to install it using
virtualenv as you on macbook but got the same error. I will try to use it
on linux.

Thanks anyway.


best regards,

Chen Jie, PhD Candidate,
Department of Systems Engineering and Engineering Management
The Chinese University of Hong Kong
***@***.***, ***@***.***

**Comment by zkytony** [comment]
OK. I might be able to help if you provide the error message on mac.

**Comment by cj9208** [comment]
Same error message as I posted on the issue : ModuleNotFoundError: No
module named 'pomdp_py.framework.basics'




(testenv2) (base) ***@***.*** ~ % python -m
pomdp_problems.tiger.tiger_problem

Traceback (most recent call last):

  File "/Users/chenjie/opt/anaconda3/lib/python3.8/runpy.py", line 194, in
_run_module_as_main

    return _run_code(code, main_globals, None,

  File "/Users/chenjie/opt/anaconda3/lib/python3.8/runpy.py", line 87, in
_run_code

    exec(code, run_globals)

  File
"/Users/chenjie/testenv2/lib/python3.8/site-packages/pomdp_problems/tiger/tiger_problem.py",
line 38, in <module>

    import pomdp_py

  File
"/Users/chenjie/testenv2/lib/python3.8/site-packages/pomdp_py/__init__.py",
line 4, in <module>

    from pomdp_py.framework.basics import *

ModuleNotFoundError: No module named 'pomdp_py.framework.basics'




best regards,

Chen Jie, PhD Candidate,
Department of Systems Engineering and Engineering Management
The Chinese University of Hong Kong
***@***.***, ***@***.***

**Comment by zkytony** [comment]
It might be because the wheel built on Linux isn't compatible with mac. You could try installing by ignoring the prebuilt wheel:
```
pip install pomdp-py --no-binary :all:
```
It shows the following on my computer
```
$ pip install pomdp-py --no-binary :all:
Collecting pomdp-py
  Downloading pomdp-py-1.2.4.5.tar.gz (101 kB)
     |████████████████████████████████| 101 kB 4.4 MB/s 
Requirement already satisfied: Cython in ./testenv2/lib/python3.8/site-packages (from pomdp-py) (0.29.24)
...)
Skipping wheel build for pomdp-py, due to binaries being disabled for it.
Installing collected packages: pomdp-py
    Running setup.py install for pomdp-py ... done
Successfully installed pomdp-py-1.2.4.5
```

**Comment by zkytony** [comment]
@cj9208 Would be great if you can try that. I'll update the documentation if it works.

**Comment by cj9208** [comment]
No, it doesn't.

The following are the output:

Found existing installation: pomdp-py 1.2.4.5

Uninstalling pomdp-py-1.2.4.5:

  Would remove:

    /Users/chenjie/testenv2/lib/python3.8/site-packages/pomdp_problems/*


/Users/chenjie/testenv2/lib/python3.8/site-packages/pomdp_py-1.2.4.5.dist-info/*

    /Users/chenjie/testenv2/lib/python3.8/site-packages/pomdp_py/*

Proceed (y/n)? y

  Successfully uninstalled pomdp-py-1.2.4.5

(testenv2) (base) ***@***.*** ~ % pip install pomdp-py
--no-binary :all:


Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple

Collecting pomdp-py

  Using cached
https://pypi.tuna.tsinghua.edu.cn/packages/a6/00/89508d1782a2fe9a0e664a543f2af8e0b8eefcf740e8c64ad278203ae5b4/pomdp-py-1.2.4.5.tar.gz
(101 kB)

Requirement already satisfied: Cython in
./testenv2/lib/python3.8/site-packages (from pomdp-py) (0.29.24)

Requirement already satisfied: numpy in
./testenv2/lib/python3.8/site-packages (from pomdp-py) (1.21.1)

Requirement already satisfied: scipy in
./testenv2/lib/python3.8/site-packages (from pomdp-py) (1.7.1)

Requirement already satisfied: matplotlib in
./testenv2/lib/python3.8/site-packages (from pomdp-py) (3.4.3)

Requirement already satisfied: pygame in
./testenv2/lib/python3.8/site-packages (from pomdp-py) (2.0.1)

Requirement already satisfied: opencv-python in
./testenv2/lib/python3.8/site-packages (from pomdp-py) (4.5.3.56)

Requirement already satisfied: networkx in
./testenv2/lib/python3.8/site-packages (from pomdp-py) (2.6.2)

Requirement already satisfied: pygraphviz in
./testenv2/lib/python3.8/site-packages (from pomdp-py) (1.7)

Requirement already satisfied: python-dateutil>=2.7 in
./testenv2/lib/python3.8/site-packages (from matplotlib->pomdp-py) (2.8.2)

Requirement already satisfied: pillow>=6.2.0 in
./testenv2/lib/python3.8/site-packages (from matplotlib->pomdp-py) (8.3.1)

Requirement already satisfied: kiwisolver>=1.0.1 in
./testenv2/lib/python3.8/site-packages (from matplotlib->pomdp-py) (1.3.1)

Requirement already satisfied: pyparsing>=2.2.1 in
./testenv2/lib/python3.8/site-packages (from matplotlib->pomdp-py) (2.4.7)

Requirement already satisfied: cycler>=0.10 in
./testenv2/lib/python3.8/site-packages (from matplotlib->pomdp-py) (0.10.0)

Requirement already satisfied: six in
./testenv2/lib/python3.8/site-packages (from
cycler>=0.10->matplotlib->pomdp-py) (1.16.0)

Skipping wheel build for pomdp-py, due to binaries being disabled for it.

Installing collected packages: pomdp-py

    Running setup.py install for pomdp-py ... done

Successfully installed pomdp-py-1.2.4.5

WARNING: You are using pip version 21.0.1; however, version 21.2.4 is
available.

You should consider upgrading via the '/Users/chenjie/testenv2/bin/python
-m pip install --upgrade pip' command.

(testenv2) (base) ***@***.*** ~ % python -m
pomdp_problems.tiger.tiger_problem

Traceback (most recent call last):

  File "/Users/chenjie/opt/anaconda3/lib/python3.8/runpy.py", line 194, in
_run_module_as_main

    return _run_code(code, main_globals, None,

  File "/Users/chenjie/opt/anaconda3/lib/python3.8/runpy.py", line 87, in
_run_code

    exec(code, run_globals)

  File
"/Users/chenjie/testenv2/lib/python3.8/site-packages/pomdp_problems/tiger/tiger_problem.py",
line 38, in <module>

    import pomdp_py

  File
"/Users/chenjie/testenv2/lib/python3.8/site-packages/pomdp_py/__init__.py",
line 4, in <module>

    from pomdp_py.framework.basics import *

ModuleNotFoundError: No module named 'pomdp_py.framework.basics'





best regards,

Chen Jie, PhD Candidate,
Department of Systems Engineering and Engineering Management
The Chinese University of Hong Kong
***@***.***, ***@***.***

**Comment by zkytony** [comment]
The only thing I can think of is somehow on mac, the `framework.cpython....so` file (should be under the pomdp_py directory in your virtualenv) doesn't work, because all the code is compiled in it. In a later release I will not compile everything into this single file but into individual `.so` files under individual paths (for example `basics.cpython...so` under `pomdp_py/framework`). In the mean time, please try to use this on Linux. Thanks!

**Comment by cj9208** [comment]
OK， I will try on a linux machine and let you know if it can work fine.

best regards,

Chen Jie, PhD Candidate,
Department of Systems Engineering and Engineering Management
The Chinese University of Hong Kong
***@***.***, ***@***.***

**Comment by zkytony** [comment]
@cj9208 Any updates?

**Comment by cj9208** [comment]
Sorry, I forgot to reply to you.

Update: It works fine on a linux machine.  For windows, it still doesn't
work.

best regards,

Chen Jie, PhD Candidate,
Department of Systems Engineering and Engineering Management
The Chinese University of Hong Kong
***@***.***, ***@***.***

**Comment by zkytony** [comment]
Thanks for the update! I will try to fix this on windows when I get a chance.

**Comment by saeedghadiri** [comment]
Hello, I get the exact same error after installing both with pip and build.

**Comment by zkytony** [comment]
@saeedghadiri I currently don't use windows very much, but I would appreciate if someone could take a dive and figure out what the fix is! I will have time to look at this in probably three weeks.

**Comment by zkytony** [comment]
Does it also not work if you clone the repo and install it as a developer?

**Comment by saeedghadiri** [comment]
I checked the library in my venv and the framework folder is empty. I'll give it a try.

**Comment by cj9208** [comment]
no, just install with pip.

best regards,

Chen Jie, PhD Candidate,
Department of Systems Engineering and Engineering Management
The Chinese University of Hong Kong
***@***.***, ***@***.***

**Comment by zkytony** [comment]
I think trying to install from source should work, that is, clone the repo, and then run `make build`. Then you won't have the issue of `.pyx` file missing.

If this is still an issue, feel free to reopen.

**Comment by zkytony** [comment]
In case anyone would like to install pomdp-py on Windows, there is a guide in [this wiki page](https://github.com/h2r/pomdp-py/wiki/Installing-pomdp-py-on-Windows).

**Comment by iseecow** [comment]
I`ve succeed in building the project on Windows, through updating the version of "pomdp_py".
While the names of file in dataset change due to filenames couldn`t contain "#" and ">". This problem could be solved through coding in run_{}.sh.
