### ISSUE TITLE
Error with  pip install -e .

### ISSUE THREAD

**Issue by cmbowyer13** [h2r/pomdp-py#2]
Hello, in the basic setup instructions after git cloning the repo, the instructions fail for me at this second command.

**Comment by cmbowyer13** [comment]
installation got hung up on the graphviz package. This command worked: pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"

**Comment by zkytony** [comment]
Glad you resolved it! The `pygraphviz` right now is just used for MCTS tree visualization. It shouldn't affect anything else if you comment out `pygraphviz` in the `setup.py`.
