### ISSUE TITLE
Using POMCP to solve a time-dependent problem

### ISSUE THREAD

**Issue by Hororohoruru** [h2r/pomdp-py#21]
Hello! First of all, I wanted to thank you for this package, I have been using it since the beginning of my PhD and it saved me a lot of work interfacing with solvers and other stuff.

I am new to POMDPs, and I am studying the possibility of using them to help decode brain signals for my thesis. So far, I have had good results using fixed windows of brain data and generating a confusion matrix from a classifier as the observation model for the POMDP, and solving it with SARSOP.

For the particular problem I am interested in, it would be beneficial to accumulate the data for every step of the model. This is, for example, instead of using a window from time 0 to time 200 for the first time step, and another from time 200 to time 400 for the second time step, I would like to use the window 0-200 for t1, and 0-400 for t2. The number of time steps and the maximum length of the window are fixed. The problem with this approach is that using more data makes the classifier that generates the confusion matrix more precise, yielding a different confusion matrix. As such, the observation model for every time step is different. 

After discussing with my supervisor, we decided to use POMCP as an algorithm, and I was wondering about the implementation. 

Until now, I implemented the ObservationModel as indexing a 2D matrix using the true state index and the observation index to represent the probabilities of p(o|s). For a variant that has a different model for every time step, a 3D confusion matrix would be required, that could be indexed by passing the observation, the state, and the time step to the ObservationModel.probability() function.

Would it be possible to implement this in the POMCP implementation of the package? Please let me know. I hope I have included all the pertinent information for the problem, otherwise please tell me and I will provide the extra detaild that may be needed. Thank you very much.

**Comment by zkytony** [comment]
Glad you are finding this useful! Thanks for the detailed description of your problem.

I think it is possible for POMCP or POUCT to be applied to your problem. If your concern is passing in the time step as an additional input, you could consider the time step as part of the state. Although time step may sound like a different concept, but fundamentally, it is an attribute of a state.

Would something like below be a place to start? 
```
import pomdp_py

class BrainSIgnalState(pomdp_py.State):
    def __init__(self, data, time_step):
        self.data = data
        self.time_step = time_step
   ... # implement __hash__ and __eq__
```
Then, when you implement the `probability` function of your observation model, you could:
```
class BrainSignalObservationModel(pomdp_py.ObservationModel):
    def probability(self, observation, next_state, action):
        time_step = next_state.time_step
        ...
```

Note that `probability` is not called during POMCP because it is a sample-based planning algorithm. The `sample` function of your observation model will be called. The `probability` function could be useful for belief update.

**Comment by Hororohoruru** [comment]
Hello! Thank you for your response. I think making the time step as part of the state is a good idea, the only problem I see is that it would increase the total number of states. 

If I have 5 states and 5 time steps for each state, and I understood correctly, that would make a total of 25 states. The problem I see with this approach is that the state does not really change with the time step, what changes is the probability of receiving a certain observation (e.g., on the first time step, using a small amount of data, the probabilities may be very similar for all observation).

What I mean is that for the model to be effective, each state would need to have the same belief regardless of the time step. On the same spirit, maybe it would make sense to make the time step an attribute of the observation? I will check the code on the POMCP algorithm to get a clearer idea of how the methods need to be implemented.

**Comment by zkytony** [comment]
I see, I think having the time step in observation is doable too.

**Comment by Hororohoruru** [comment]
I'll have a go at it during the summer. Thank you for your advice, I will start from your suggestion!
