### ISSUE TITLE
Making a greedy rollout policy for POMCP

### ISSUE THREAD

**Issue by Hororohoruru** [h2r/pomdp-py#34]
Hello! In tuning with my particular problem, I am exploring potential solutions to some problems I'm having related to the different steps of the POMCP simulation. One of them is to change the rollout policy used to add new nodes to the tree.

Right now, the POMCP is using a random rollout that returns any actions with a uniform probability. I would like to implement a rollout that always selects the action with the highest immediate value, but it is not clear to me how to code it with the existing `PolicyModel` interface.

**Comment by zkytony** [comment]
Check out [this documentation](https://h2r.github.io/pomdp-py/html/examples.action_prior.html). You can implement your own `rollout` function. 

I am not sure what you mean by "highest immediate value", but in the `rollout` function, you have access to the state (and possibly history). You can compute some forward simulations from that state to get a value estimate according to some heuristic policy.

**Comment by Hororohoruru** [comment]
I mean to take the action with the highest Q-value instead of a random action. Is that possible?

**Comment by zkytony** [comment]
How would you have access the to Q value during rollout?

**Comment by Hororohoruru** [comment]
After having a look at the code and other sources I realize it does not make sense since the rollout simulations are what give an estimate to the value on the first place...

But for example, couldn't the [rollout function](https://github.com/h2r/pomdp-py/blob/85d9a3182e6a883e44315617c9fdfde484d05c01/pomdp_py/algorithms/po_uct.pyx#L389) be called with the current belief of the Vnode? Then the rollout could perform a random selection weighted on the current belief.

**Comment by zkytony** [comment]
Sure, you can sample from current belief and call the rollout function. I believe that's what [PORollout](https://github.com/h2r/pomdp-py/blob/85d9a3182e6a883e44315617c9fdfde484d05c01/pomdp_py/algorithms/po_rollout.pyx#L55) does.

**Comment by Hororohoruru** [comment]
I see, but that is to sample the state in the `_search` method. If I am not mistaken, [PO_UCT](https://github.com/h2r/pomdp-py/blob/85d9a3182e6a883e44315617c9fdfde484d05c01/pomdp_py/algorithms/po_uct.pyx#L312C28-L312C28) does the same.

However, I would like to do that during rollout.

**Comment by zkytony** [comment]
Yes, I think you would have to figure out your own implementation for that.

**Comment by Hororohoruru** [comment]
Great, thanks! I'll close the issue then.
