### ISSUE TITLE
POUCT and belief update

### ISSUE THREAD

**Issue by khuechuong** [h2r/pomdp-py#72]
So I've been trying to figure out how the code in POUCT utilize the belief update, but I can't find any. In po_uct.pyx, the only time it utilizes belief is sample_belief in the _search() function for simulations. The tree seems to be action -> observation -> action-> etc. and I can't find any "current belief" being utilize.

When I comment out the update_histogram_belief in the tiger problem, the planner doesn't work so clearly, the planner is utilizing it, I'm just not sure how. 

If anyone has any inputs, that would be nice! Thank you!

**Comment by zkytony** [comment]
POUCT draws samples from the belief and pass them down the tree.

**Comment by khuechuong** [comment]
@zkytony ya I notice the sample_belief function which does that, but that's the only instant I see. POUCT.plan takes in the agent and did simulation with many samples to build/update the search tree where root is observation. At the end, it takes the action with highest value. However, I don't see it utilizing the value of distribution of current belief. 

Also, when it is building the tree with a bunch of samples where target is in different positions, wouldn't the tree just be filled with a bunch of different position observations?

**Comment by khuechuong** [comment]
Or is it that since there's so many random ones that the real one is in 1 of the branch which then makes that the root and prunes all the other ones?

**Comment by zkytony** [comment]
Don't hallucinate. Please take a pass at Algorithm 1 in the [POMCP paper](https://papers.nips.cc/paper_files/paper/2010/file/edfbe1afcf9246bb0d40eb4d8027d90f-Paper.pdf). The essence is each node (corresponding to history h) in the tree stores an estimate of V(h).

If you'd like to see what's in the tree, you can check out tree debugger: https://h2r.github.io/pomdp-py/html/api/pomdp_py.utils.debugging.html
